alias: Handle WoL webhook
description: ''
triggers:
  - trigger: webhook
    allowed_methods:
      - POST
    local_only: false
    webhook_id: -ExxxxxxxxxxxxxxxxHs
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.json.event == ''started'' }}'
        sequence:
          - action: notify.send_message
            metadata: {}
            target:
              entity_id: notify.my_iphone
            data:
              title: 'WOL: Started'
              message: The WoL Forwarder App (re)started
        alias: Restarted
      - conditions:
          - condition: template
            value_template: '{{ trigger.json.event == ''forwarded'' }}'
        sequence:
          - action: notify.send_message
            metadata: {}
            target:
              entity_id: notify.my_iphone
            data:
              title: '{{ ''WOL: ''~trigger.json.event}}'
              message: >-
                {{'Target '~trigger.json.mac_name~' Waked by
                '~trigger.json.source_name}}
        alias: Forwarded packets
      - conditions:
          - condition: template
            value_template: '{{ trigger.json.event == ''rejected'' }}'
        sequence:
          - action: notify.send_message
            metadata: {}
            target:
              entity_id: notify.my_iphone
            data:
              title: '{{ ''WOL: ''~trigger.json.event}}'
              message: '{{''Rejected ''~trigger.json.message }}'
         alias: Rejected packets
mode: single

