name: Daily Image Cleanup
#Keep 10 tagged images plus dev, drop everything else
on:
#  schedule:
#    - cron: '30 1 * * *'
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          keep-n-tagged: 5
          exclude-tags: dev
          delete-untagged: true
          delete-partial-images: true
          dry-run: true
