name: Daily Image Cleanup
#Keep 10 tagged images plus dev, drop everything else
on:
#  schedule:
#    - cron: '30 1 * * *'
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          keep-n-tagged: 2
          exclude-tags:  1.1.2,1.2.1,1.3.0,1.3.1
          #delete-tags: 1.2.0b1,1.2.0-rc,1.2.0
          delete-untagged: true
          delete-partial-images: true
          #dry-run: true
